### ISSUE TITLE
Dialog or Modal sometimes freezes in the open state after closing

### ISSUE THREAD

**Issue by gregmsanderson** [zaichaopan/react-aria-components-tailwind-starter#20]
When opening a Dialog or Modal, or a component that uses them (like Autocomplete), they often freeze open.

For example:

https://zaichaopan.github.io/react-aria-components-tailwind-starter/?path=/docs/dialog--docs

... click the button to open the dialog, it's fine. If you then close it (whether by clicking cancel, the background overlay, or the close button), it _starts_ to close for a fraction of a second, but then pops back open again, and freezes open in that state. It then can't be closed. Clicking any of the buttons does not close it. You have to reload the whole page to reset the state. Then it works again.

_While_ it's stuck open, you can see the form etc within it is still working. It's just not closable. So React isn't frozen, or anything like that.

Confusingly it's not every time. Sometimes you can close a dialog, open it, close it, and then it freezes open. In the recording below you can see the first time, it _does_ close. All good. I then re-open it, close it, and _then_ it freezes open, on the second close.

There is no error in the console.

Also: normally when the Dialog is open, the page can _not_ be scrolled. That is correct. It traps focus. However when it's frozen in the open state, the page _can_ be scrolled up and down behind it.

You can see in the video that the second time it's closed (at 00:09), it _starts_ to close for a fraction of a second, then immediately shows as open, despite not being re-opened. It's then stuck open until I reload the page at 00:25 (which of course closes it). I then re-open it, and then it's the _third_ time of closing it that it freezes open. Weird!

https://github.com/user-attachments/assets/bd0a2d7d-e9b7-4a33-ab96-e76122def9c1

**Comment by zaichaopan** [comment]
Thanks for reporting the issue. Are you using a Windows machine?  I cannot reproduce the issue on Mac. But I can see the issue happen on Windows. I am not sure if it is React Aria or Storybook issue. I will spend time playing around to see what the issues is.

**Comment by gregmsanderson** [comment]
Strange. I'm on a Mac too. This was in Chrome.

The Tailwind preview Storybook (on the Aria site) seems to work fine. At least I can't get that one to get stuck open. I installed all the latest ones too (locally) and still get it.

**Comment by gregmsanderson** [comment]
Ah, it _seemed_ fixed with that version, but on the fifth time, it froze again.

I'm using Chrome 139 on Mac.

**Comment by zaichaopan** [comment]
Thanks for helping test. I find a  similar issue reported in react aria GitHub https://github.com/adobe/react-spectrum/issues/8802. I will try a few things to see if we can still get the exiting animation which feels better than without it.

**Comment by gregmsanderson** [comment]
Ok, I've been experimenting too and I _think_ I've fixed it.

I tried commenting out various classes. It only seems to consistently and reliably close when the `data-exiting:duration-X` class is _not_ present. The duration doesn't seem to matter. Eventually it freezes open.

Apparently the default is 150ms which I think still looks fine. Personally I'd rather it be 150ms faster _and_ close reliably than be _ever_ so slightly prettier and freeze half the time.

So my fix is simply to comment out the exiting time and opt for 150ms. So far it hasn't frozen.

```tsx
 <RACModalOverlay
      {...props}
      {...(isOpen !== undefined && {
        isOpen,
      })}
      {...(onOpenChange !== undefined && {
        onOpenChange,
      })}
      data-ui="modal-overlay"
      className={composeTailwindRenderProps(classNames?.modalOverlay, [
        "fixed top-0 left-0 isolate z-20",
        "h-(--visual-viewport-height) w-full",
        "bg-zinc-950/25 dark:bg-zinc-950/50",
        "text-center",
        "data-entering:animate-in",
        "data-entering:fade-in",
        //"data-entering:duration-150",
        "data-entering:ease-out",
        "data-exiting:animate-out",
        "data-exiting:fade-out",
        //"data-exiting:duration-150",
        "data-exiting:ease-in",
```

and later

```tsx
<RACModal
        {...props}
        data-ui="modal"
        data-placement={placement}
        className={composeTailwindRenderProps(classNames?.modal, [
          "relative max-h-full w-full overflow-hidden",
          "text-left align-middle",
          "shadow-lg",
          "bg-background",
          "ring-1 ring-zinc-950/5 dark:ring-zinc-800",

          props.size
            ? sizes[props.size]
            : "sm:has-[[role=alertdialog]]:max-w-md sm:has-[[role=dialog]]:max-w-lg",

          "data-entering:animate-in",
          "data-entering:ease-out",
          //"data-entering:duration-150",
          "data-exiting:animate-out",
          "data-exiting:ease-in",
          //"data-exiting:duration-150",
```

**Comment by zaichaopan** [comment]
Thanks a lot for the investigation!  The fix is great! Would you like to submit a PR for the fix?

**Comment by zaichaopan** [comment]
Thanks a lot for the PR! I have merged it.

**Comment by kylemh** [comment]
did either of you happen to have a custom scrollbar color?
